# Generated by Django 5.2.1 on 2025-05-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuneinmeapp', '0003_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
    ]
