# Generated by Django 5.2.1 on 2025-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuneinmeapp', '0004_remove_userprofile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_challenge_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
